version: 2

models:
  - name: dim_usuario
    columns:
      - name: usuario_key
        tests:
          - unique
          - not_null

  - name: dim_rol
    columns:
      - name: rol_key
        tests:
          - unique
          - not_null

  - name: dim_aula
    columns:
      - name: aula_key
        tests:
          - unique
          - not_null

  - name: dim_materia
    columns:
      - name: materia_key
        tests:
          - unique
          - not_null

  - name: dim_grupo
    columns:
      - name: grupo_key
        tests:
          - unique
          - not_null

  - name: dim_fecha
    columns:
      - name: fecha_key
        tests:
          - unique
          - not_null

  - name: dim_horario
    columns:
      - name: horario_key
        tests:
          - unique
          - not_null

  - name: fact_accesos
    columns:
      - name: acceso_key
        tests:
          - not_null
      - name: usuario_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_usuario')
              field: usuario_key
      - name: aula_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_aula')
              field: aula_key
      - name: fecha_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_fecha')
              field: fecha_key
